#!/usr/bin/env bash
# TrendHub SPA 빌더 dist → onoff-builder-bridge imports 동기화
# 주의: linkconnect/onoffcpa 저장소의 SPA 번들을 여기로 복사하면 안 됨(브랜드/카피 분리).
# 반드시 trendhub/builder/linkconnect_source 에서 npm run deploy:imports 로만 갱신.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/builder/linkconnect_source/dist"
PUBLIC="$ROOT/builder/linkconnect_source/public"
DEST="$ROOT/plugin/onoff-builder-bridge/imports/linkconnect"
LOCK="$DEST/spa-brand.trendhub"

case "$ROOT" in
  */trendhub) ;;
  *)
    echo "sync-linkconnect-builder: REFUSE — ROOT 가 trendhub 가 아님: $ROOT" >&2
    echo "  linkconnect/onoffcpa 저장소 SPA 를 이 경로로 넣지 마세요." >&2
    exit 1
    ;;
esac

if [[ ! -d "$SRC" ]]; then
  echo "dist 없음. 먼저 실행: cd builder/linkconnect_source && npm run build" >&2
  exit 1
fi

bash "$ROOT/scripts/assert-trendhub-spa-branding.sh" "$SRC/index.html"

mkdir -p "$DEST/assets"
rsync -a --delete \
  --exclude '._*' \
  --exclude '.DS_Store' \
  --exclude '*.map' \
  --exclude 'spa-brand.trendhub' \
  --exclude 'spa-brand.onoffcpa' \
  --exclude 'BRANDING.md' \
  "$SRC/assets/" "$DEST/assets/"
cp "$SRC/index.html" "$DEST/index.html"

if [[ -d "$PUBLIC" ]]; then
  rsync -a \
    --exclude '._*' \
    --exclude '.DS_Store' \
    --exclude 'spa-brand.trendhub' \
    --exclude 'spa-brand.onoffcpa' \
    --exclude 'BRANDING.md' \
    "$PUBLIC/" "$DEST/"
fi

cat > "$LOCK" <<'EOF'
brand=trendhub
# Generated by scripts/sync-linkconnect-builder.sh — do not copy from linkconnect/onoffcpa.
EOF

# Remove legacy onoffcpa lock if present
rm -f "$DEST/spa-brand.onoffcpa"

find "$DEST" -name '._*' -delete 2>/dev/null || true
find "$DEST" -name '.DS_Store' -delete 2>/dev/null || true

bash "$ROOT/scripts/assert-trendhub-spa-branding.sh" --require-lock "$DEST/index.html"

echo "Synced: $SRC -> $DEST"
ls -la "$DEST/assets"
